# Triggers a build when a new commit is pushed to main.
---
name: Application (main)
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.env.os }}
    strategy:
      fail-fast: false
      matrix:
        env:
          - name: linux
            os: ubuntu-latest
            ninja_platform: linux
            qt_platform: linux
            arch: linux-x86_64
            cmake_env: {}
          - name: mac
            os: macos-latest
            ninja_platform: mac
            qt_platform: mac
            arch: darwin64-x86_64-cc
            cmake_env: {}
          - name: win
            os: windows-latest
            ninja_platform: win
            qt_platform: windows
            arch: VC-WIN64A
            cmake_env:
              CC: cl
              CXX: cl
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
...